# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{radiant-mailer-extension}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nathaniel Talbott", "Sean Cribbs", "Matt McCray"]
  s.date = %q{2010-04-21}
  s.description = %q{An extension for Radiant CMS that allows you to create 'contact us' and other mail-bound forms.}
  s.email = %q{radiant@radiantcms.org}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "app/controllers/mail_controller.rb",
     "app/models/mail.rb",
     "app/models/mailer.rb",
     "lib/mailer_process.rb",
     "lib/mailer_tags.rb",
     "lib/radiant-mailer-extension.rb",
     "lib/tasks/mailer_extension_tasks.rake",
     "mailer_extension.rb",
     "radiant-mailer-extension.gemspec",
     "spec/controllers/mail_controller_spec.rb",
     "spec/dataset/mailer_dataset.rb",
     "spec/lib/mailer_process_spec.rb",
     "spec/lib/mailer_tags_spec.rb",
     "spec/models/mail_spec.rb",
     "spec/models/mailer_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/radiant/radiant-mailer-extension}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Enables form mail on a page.}
  s.test_files = [
    "spec/controllers/mail_controller_spec.rb",
     "spec/dataset/mailer_dataset.rb",
     "spec/lib/mailer_process_spec.rb",
     "spec/lib/mailer_tags_spec.rb",
     "spec/models/mail_spec.rb",
     "spec/models/mailer_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

